repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0  # Use the ref you want to point at
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://taro-station.usc.edu:20443/AnalysisPipeline/hlab-pre-commit-hook.git
  rev: v1.0.0
  hooks:
  - id: julia-formatter
